package org.prevayler.demos.scalability.prevayler;

import java.io.File;

import org.prevayler.PrevaylerFactory;
//import org.prevayler.implementation.PrevalenceTest;

public class PrevaylerTransactionSubject extends PrevaylerScalabilitySubject {

	public PrevaylerTransactionSubject(String journalDirectory) throws java.io.IOException, ClassNotFoundException {
		if (new File(journalDirectory).exists()) PrevalenceTest.delete(journalDirectory);
		prevayler = PrevaylerFactory.createPrevayler(new TransactionSystem(), journalDirectory);  //No snapshot is generated by the test.
	}


	public Object createTestConnection() {
		return new PrevaylerTransactionConnection(prevayler);
	}
}
