package org.prevayler.demos.scalability.prevayler;

import java.io.File;
import java.io.IOException;

import org.prevayler.PrevaylerFactory;

public class PrevaylerTransactionSubject extends PrevaylerScalabilitySubject {

	private final String _logDirectory;
	
	public PrevaylerTransactionSubject(String logDirectory) throws java.io.IOException, ClassNotFoundException {
		_logDirectory = logDirectory;
		if (new File(_logDirectory).exists()) PrevalenceTest.delete(_logDirectory);
		initializePrevayler();
	}

	public Object createTestConnection() {
		return new PrevaylerTransactionConnection(prevayler);
	}
	
	public boolean isConsistent() throws Exception {
		int expectedResult = prevayler.prevalentSystem().hashCode();
		initializePrevayler();  //Will reload all transactions from the log files.
		return prevayler.prevalentSystem().hashCode() == expectedResult;
	}

	private void initializePrevayler() throws IOException, ClassNotFoundException {
		prevayler = PrevaylerFactory.createPrevayler(new TransactionSystem(), _logDirectory);  //No snapshot is generated by the test.
	}
}
