// Prevayler(TM) - The Open-Source Prevalence Layer.
// Copyright (C) 2001 Klaus Wuestefeld.
// This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.

package org.prevayler.test.scalability.prevayler;

import org.prevayler.implementation.*;
import org.prevayler.test.PersistenceTest;

public class PrevaylerManipulationSubject extends PrevaylerScalabilitySubject {

	public PrevaylerManipulationSubject(String[] logDirectories) throws java.io.IOException, ClassNotFoundException {
		for (int i = 0; i < logDirectories.length; i++) {
			PersistenceTest.deletePrevalenceFiles(logDirectories[i]);
		}

		prevayler = new SnapshotPrevayler(new ManipulationSystem(), logDirectories, logDirectories[0]);  //No snapshot is generated by the test so the snapshot directory can be the same as the first log directory.
	}


	public Object createTestConnection() {
		return new PrevaylerManipulationConnection(prevayler);
	}
}
